{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.deployment.name . }}
  {{- if .Values.deployment.annotations }}
  annotations: {{ tpl (toYaml .Values.deployment.annotations) . | nindent 4 }}
  {{- end }}
  labels: {{ tpl (toYaml .Values.deployment.labels) . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ tpl (toYaml .Values.deployment.labels) . | nindent 6 }}
  {{- if .Values.deployment.replicas }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.deployment.annotations }}
      annotations: {{ tpl (toYaml .Values.deployment.annotations) . | nindent 8 }}
      {{- end }}
      labels: {{ tpl (toYaml .Values.deployment.labels) . | nindent 8 }}
    spec:
      topologySpreadConstraints: {{ tpl (toYaml .Values.deployment.topologySpreadConstraints) . | nindent 8 }}
      affinity: {{ tpl (toYaml .Values.deployment.affinity) . | nindent 8 }}
      containers: 
        {{- range .Values.deployment.containers }}
        - name: {{ tpl .name $ }}
          image: {{ tpl .image.repository $ }}:{{ tpl .image.tag $ }}
          imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
          {{- if .command }}
          command: {{ tpl (toYaml .command) $ | nindent 12 }}
          {{- end }}
          {{- if .ports }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          {{- if .resources }}
          resources: {{ tpl (toYaml .resources) $ | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe: {{ tpl (toYaml .readinessProbe) $ | nindent 12 }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe: {{ tpl (toYaml .livenessProbe) $ | nindent 12 }}
          {{- end }}
          {{- if .securityContext }}
          securityContext: {{ tpl (toYaml .securityContext) $ | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- if .env.default }} 
            {{- range .env.default }}
            {{- range $k, $v := . }}
            - name: {{ tpl $k $ }}
              value: {{ tpl ($v | toString) $ | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .env.valueFrom }}
            {{- range .env.valueFrom }}
            {{- range $k, $v := . }}
            - name: {{ tpl $k $ }}
              valueFrom: {{ tpl (toYaml $v) $ | nindent 16 }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if .envFrom }}
          envFrom: {{ tpl (toYaml .envFrom) $ | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts: {{ tpl (toYaml .volumeMounts) $ | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets: {{ tpl (toYaml .Values.deployment.imagePullSecrets) . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      serviceAccountName: {{ tpl (or .Values.deployment.serviceAccountName .Values.deployment.serviceAccount) . }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .Values.deployment.nodeSelector) . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes: {{ tpl (toYaml .Values.deployment.volumes) . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.securityContext }}
      securityContext: {{ toYaml .Values.deployment.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations: {{ tpl (toYaml .Values.deployment.tolerations) . | nindent 8 }}
      {{- end -}}
{{- end -}}
