{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .Values.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.labels }}
  labels: {{ tpl (toYaml .Values.serviceAccount.labels) . | nindent 4 }}
  {{- end }}
  name: {{ tpl .Values.serviceAccount.name . }}
{{- end -}}
