---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: default
data:
  enabled-namespaces: "default,production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-webhook
  template:
    metadata:
      labels:
        app: validation-webhook
    spec:
      containers:
      - name: webhook
        image: aozer/validation-webhook:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
        - name: webhook-config
          mountPath: /etc/config
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
      - name: webhook-config
        configMap:
          name: webhook-config

---
apiVersion: v1
kind: Service
metadata:
  name: validation-webhook
  namespace: default
spec:
  selector:
    app: validation-webhook
  ports:
    - port: 443
      targetPort: 8080

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: deployment-validation
webhooks:
- name: deployment-validation.default.svc
  clientConfig:
    service:
      name: validation-webhook
      namespace: default
      path: "/validate"
    caBundle: ${CA_BUNDLE}
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["deployments"]
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"]
