---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for App X pods only."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-x
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-x
  template:
    metadata:
      labels:
        app: app-x
    spec:
      priorityClassName: high-priority
      containers:
      - name: app-x
        image: app-x:latest
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-x-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-x
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: app-x-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: app-x
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-y
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-y
  template:
    metadata:
      labels:
        app: app-y
    spec:
      containers:
      - name: app-y
        image: app-y:latest
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-y-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi